### ISSUE TITLE
pify and couchnode

### ISSUE THREAD

**Issue by sm2017** [sindresorhus/pify#64] opened 2018-08-26 11:59 UTC
@sindresorhus How can I use pify to Promisify couchnode ? 
I tried both **Promisify a single function** and **Promisify all methods in a module** approach .

https://github.com/couchbase/couchnode

**Comment by sindresorhus** [comment] 2018-09-06 09:38
It's a class, so you need to bind the instance/method before promisifying it.

**Comment by sindresorhus** [comment] 2019-09-23 09:37
Duplicate of #57

**Closed by sindresorhus** 2019-09-23 09:37 UTC
