### ISSUE TITLE
Example of excludeMain option is not correct

### ISSUE THREAD

**Issue by DanSnow** [sindresorhus/pify#39] opened 2017-02-16 04:08 UTC
~~~js
fn.method = (data, callback) => {
    setImmediate(() => {
        callback(data, null);
    });
};
~~~
Here call the `callback` with `data, error` order .  
But the order  shouldn't be `error, data`?  

~~~js
promiseFn.method('hi').then(data => {
    console.log(data);
});
~~~
The promise return by the `method`  will be rejected.
Here is a [code snippet](https://runkit.com/580653313ae4d20014daca61/58a5227a25e6da001336b9b5) on runkit.

**Comment by schnittstabil** [comment] 2017-02-16 07:37
Pify only supports only _Node.js style callbacks_, from the [API documentation](https://nodejs.org/api/errors.html#errors_node_js_style_callbacks):
> […] the callback function is called with the Error object (if any) passed as the first argument. If no error was raised, the first argument will be passed as `null`.
> ```js
> function nodeStyleCallback(err, data) {…}
> ```

@DanSnow Thus your issue is somehow a duplicate of #31.

**Closed by schnittstabil** 2017-02-16 07:37 UTC

**Comment by DanSnow** [comment] 2017-02-16 09:34
I'm requesting a support for non-Node.js style API.
I mean that current [readme.md](https://github.com/sindresorhus/pify/blob/master/readme.md) has an error in examples.
I have opened a pull request #40.

**Comment by schnittstabil** [comment] 2017-02-16 09:38
:+1: Many thanks for clarification.
